version: "3.9"

services:
  mysql-lib:
    image: mysql:8.4
    container_name: library-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library

    ports:
      - "3309:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build:
      context: ./web

    container_name: library-flask

    ports:
      - "9000:5000"

    depends_on:
      - mysql-lib

volumes:
  mysql_data: